[package]
name = "git-delete-merged-branches"
version = "0.2.1"
authors = ["Sébastien Job <sebastien.job@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
git2 = "0.20"
openssl-sys = { version = "0.9", features = ["vendored"] }
