name: Release

# When pushing a tag name starting with `v`:
# - Build archives containing the Linux, Windows and macOS compiled versions.
# - Create a GitHub release with release notes and the archives.

on:
  push:
    tags:
      - "v*"

jobs:
  linux_build:
    name: Linux build
    uses: ./.github/workflows/rust-build.yml
    with:
      os: linux
      arch: x86
  windows_build:
    name: Windows build
    uses: ./.github/workflows/rust-build.yml
    with:
      os: windows
      arch: x86
  macos_x86_build:
    name: macOS x86 build
    uses: ./.github/workflows/rust-build.yml
    with:
      os: macos
      arch: x86

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [linux_build, windows_build, macos_x86_build]
    steps:
      - name: Download all archives
        uses: actions/download-artifact@v3
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ${{ needs.linux_build.outputs.artifact_name }}/${{ needs.linux_build.outputs.artifact_path }}
            ${{ needs.windows_build.outputs.artifact_name }}/${{ needs.windows_build.outputs.artifact_path }}
            ${{ needs.macos_x86_build.outputs.artifact_name }}/${{ needs.macos_x86_build.outputs.artifact_path }}
          generateReleaseNotes: true
          allowUpdates: true
          omitBodyDuringUpdate: true
      - name: Update Homebrew Formula
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: splo
          homebrew_tap: homebrew-tap
          formula_folder: Formula
          github_token: ${{ secrets.TAP_GITHUB_TOKEN }}
          commit_owner: splo
          commit_email: splo@users.noreply.github.com
          depends_on: |
            "git" => :optional
          install: bin.install 'git-delete-merged-branches'
          test: |
            'assert_match(/git-delete-merged-branches$/, shell_output("which git-delete-merged-branches"), "Not correctly installed")'
          target_darwin_amd64: true
          target_darwin_arm64: false
          target_linux_amd64: true
          target_linux_arm64: false
          update_readme_table: true
